before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

    ldflags:
      - -X 'github.com/antham/wo/internal/cmd.appVersion={{.Version}}'
universal_binaries:
nfpms:
  -
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    maintainer: Anthony HAMON <hamon.anth@gmail.com>
aurs:
  -
    homepage: "https://github.com/antham/wo"
    description: "Workspace shell manager"
    maintainers:
      - "Anthony HAMON <hamon.anth@gmail.com>"
    license: "MIT"
    private_key: "{{ .Env.ARCHLINUX_REPO_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/wo-bin.git"

brews:
  -
    name: wo
    homepage: "https://github.com/antham/wo"
    description: "Workspace shell manager"
    license: "MIT"
    repository:
      owner: antham
      name: wo-homebrew
      git:
        url: 'git@github.com:antham/wo-homebrew.git'
        private_key: '{{ .Env.HOMEBREW_REPO_KEY }}'
