FROM golang:alpine

RUN apk add bash fish zsh

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -o /usr/local/bin/wo main.go

RUN bash e2e-scripts/test.bash
