// Code generated by mockery v2.43.1. DO NOT EDIT.

package completion

import (
	workspace "github.com/antham/wo/internal/workspace"
	mock "github.com/stretchr/testify/mock"
)

// mockWorkspaceManager is an autogenerated mock type for the workspaceManager type
type mockWorkspaceManager struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *mockWorkspaceManager) Get(_a0 string) (workspace.Workspace, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 workspace.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (workspace.Workspace, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) workspace.Workspace); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(workspace.Workspace)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *mockWorkspaceManager) List() ([]workspace.Workspace, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []workspace.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]workspace.Workspace, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []workspace.Workspace); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]workspace.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockWorkspaceManager creates a new instance of mockWorkspaceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockWorkspaceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockWorkspaceManager {
	mock := &mockWorkspaceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
