name: E2E tests

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read

env:
  TAG: e2e

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          file: ./Dockerfile.test
          tags: ${{ env.TAG }}
      - name: Run bash tests
        run: |
          docker run --rm ${{ env.TAG }} bash e2e-scripts/test /usr/src/app/e2e-scripts/init.bash
      - name: Run sh tests
        run: |
          docker run --rm ${{ env.TAG }} sh e2e-scripts/test /usr/src/app/e2e-scripts/init.sh
